/**
 * Common types
 */

export const INIT = 'INIT';
export const SAVE = 'SAVE';

/**
 * Module Blockchain types
 */

export const SUBSCRIBE_BLOCKCHAIN = 'SUBSCRIBE_BLOCKCHAIN';
export const UNSUBSCRIBE_BLOCKCHAIN = 'UNSUBSCRIBE_BLOCKCHAIN';
export const RESET_BLOCKCHAIN = 'RESET_BLOCKCHAIN';

export const SOCKET_ONOPEN = 'SOCKET_ONOPEN';
export const SOCKET_ONCLOSE = 'SOCKET_ONCLOSE';
export const SOCKET_ONERROR = 'SOCKET_ONERROR';
export const SOCKET_ONMESSAGE = 'SOCKET_ONMESSAGE';
export const SOCKET_RECONNECT = 'SOCKET_RECONNECT';
export const SOCKET_RECONNECT_ERROR = 'SOCKET_RECONNECT_ERROR';

/**
 * Module Desktop types
 */

export const ADD_WIDGET = 'ADD_WIDGET';
export const UPDATE_DIMENSIONS = 'UPDATE_DIMENSIONS';
export const UPDATE_POSITION = 'UPDATE_POSITION';
export const UPDATE_ZINDEX = 'UPDATE_UPDATE_ZINDEX';
export const UPDATE_VISIBILITY = 'UPDATE_VISIBILITY';
